import { defineConfig, devices } from "@playwright/test";
import baseConfig from './playwright.config';

/**
 * Playwright configuration for Live Integration tests
 *
 * Runs against local preview build (with emulators) but uses REAL Google APIs.
 * Requires:
 * - E2E_GOOGLE_CLIENT_ID
 * - E2E_GOOGLE_CLIENT_SECRET
 * - E2E_GOOGLE_DRIVE_REFRESH_TOKEN
 * - ... other E2E_* vars
 */

// Override specific settings
export default defineConfig({
  ...baseConfig,
  testDir: "./e2e/live",
  // Allow longer timeout for real network calls
  timeout: 60000, 
  // No retries for live tests to avoid burning quota/state confusion? 
  // Or retries to handle flake? Design doc says "Retry only on known transient...".
  // Playwright retries are general. Let's keep 0 for now or 1.
  retries: 1,

  // Use the same webServer, but we need to inject the REAL Client ID via ENV
  webServer: {
    ...baseConfig.webServer,
    env: {
      ...baseConfig.webServer?.env,
      // Inject Real Google Config for the Frontend to pick up
      VITE_GOOGLE_DRIVE_CLIENT_ID: process.env.E2E_GOOGLE_CLIENT_ID || "",
      VITE_GOOGLE_DRIVE_FOLDER_ID: process.env.E2E_GOOGLE_DRIVE_FOLDER_ID || "",
      // Ensure we have correct scopes
      VITE_GOOGLE_DRIVE_SCOPES: "https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/photoslibrary.readonly",
    },
  },
  
  projects: [
    {
      name: 'setup',
      testMatch: /auth\.setup\.ts/, // Matches e2e/live/auth.setup.ts
    },
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        // Use the auth state generated by setup
        storageState: 'e2e/live/.auth/user.json',
      },
      dependencies: ['setup'],
    },
  ]
});
